### ISSUE TITLE
SMTP: not recognizing a server waiting for STARTTLS

### ISSUE THREAD

**Issue by noseshimself** [elmasy-com/elmasy#4]
According to the feature list, SMTP with STARTTLS should be recognized. The feature is not working at several known mailers when connecting to Port 587/TCP.

**Comment by g0rbe** [comment]
The document is unclear about this. I working on it.
The StartTLS is currently not supported, it is in the *should know* state

**Comment by g0rbe** [comment]
Fixed  the formatting, now its a task list.
